spring:
  application:
    name: hibernate
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  jpa:
    open-in-view: true
    show-sql: false
    database-platform: mysql
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    jpa:
      repositories:
        enabled: true
  mvc:
    favicon:
      enabled: true

  profiles:
    active: dev

server:
  error:
    path: /404.html

